# Generated by Django 6.0.1 on 2026-01-13 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('scifi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('biography', 'Biography'), ('history', 'History'), ('selfhelp', 'Self-Help')], max_length=50)),
                ('date_finished', models.DateField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
