# Generated by Django 6.0.1 on 2026-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_date_finished_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
