# Generated by Django 6.0.1 on 2026-01-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
