# Generated by Django 6.0.1 on 2026-01-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='purchase_link',
        ),
    ]
