# Generated by Django 6.0.1 on 2026-02-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_status_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
