# ===== DEMO BOOKS =====
DEMO_BOOKS = [
    {
        "title": '1984',
        "author": 'George Orwell',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Disturbingly relevant. A chilling look at surveillance and power.',
        "date_finished": '2024-09-21',
        "purchase_link": 'https://www.amazon.com/1984-George-Orwell/dp/1328869334/ref=tmm_hrd_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.j8z-cLWRUg8sbRPWeuw4s-_GbuLTMrrJgv2rhI17SLsxQ8ukKgfJVGYEahS7H5SCntoGp4MBvAVYRxejINJACiOFuAV-KybmZ7lL-lEJVanWAK70c6eOXTYglXtsjlRW54MeAh7WxhshmY1mWVHGiS0wjlmavinHzw3eKpAxBu9PT7DpEi7cKWtdWAbs_2n3E8qyouBXjZ5NMVaK5zV5ytFpuEFj_yNIQBkahFOBuAM.Hor0IO4Fhnl3_ifGoqUuTW3-NH7qZbskmWCA2pdxG-U&qid=1771695987&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/1984_xi9gf3',
    },
    {
        "title": 'Atomic Habits',
        "author": 'James Clear',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 5,
        "review": 'Extremely practical and easy to apply. The habit stacking concept alone made this worth reading. One of the most actionable books I’ve read.',
        "date_finished": '2025-01-14',
        "purchase_link": 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299/ref=tmm_hrd_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.aVjxsZgNHJ6wfgiZ01PPLMHaPE-CV51Y-37RwPAsVpkfiNrR-GZoRB84iw1gt94fQ0JXF5SIkjUVqcaH_w-ZXzhzrzhC732rVp8nQ_xjoHzPkmzfHz2khUHLHmk_ZBg-ogTBtYgctc0pB8ntr38c2hUDpHJSjX6jLIi9KFvVfQNYkacnXCLfYpwfhABD_M9ZSEaeM5ggdhyedIf-G6R8nykHWg-Y0P8y85ulF9zgD6c.BUOScYNaNo6ukKtoxGNbjs7auBgwoEadTsXguDrX95k&qid=1771618896&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/atomichabits_jvxe7j',
    },
    {
        "title": 'Brave New World',
        "author": 'Aldous Huxley',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Thought-provoking social commentary.',
        "date_finished": '2024-03-14',
        "purchase_link": 'https://www.amazon.com/Brave-New-World-Aldous-Huxley/dp/0060850523/ref=sr_1_1?crid=TF48N0D6WBJL&dib=eyJ2IjoiMSJ9.LtN0ywD7uDMGDeDLLoC6CStBFiBz93slvE270Yni7pozzhQ1n6oL65Gxh1REnsLn-OFYpfHKa6CXFe3Wnitc4gl5ekjoxH3ppuNNVDb24s-6iBkSHw6emQJdNbrGIcNt8MrgsTzkJ3r5ff37D2as8LD3GeMHuSzzZaGFRwC7lYEoncZ5BEFYXTrfXGgcxa_pE8HIQMs4cTzhPKSDdTqCzFQOP0s-BtTqYGcWj3C75IU.CfCxE3B4Jhc1DQ3o-NXku834-BuVHb6BPY-2JbEtu5A&dib_tag=se&keywords=brave+new+world&qid=1771794582&s=books&sprefix=brave+new+world%2Cstripbooks%2C132&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/bravenewworld_fvf2el',
    },
    {
        "title": 'Clean Code',
        "author": 'Robert C. Martin',
        "genre": 'nonfiction',
        "status": 'currently_reading',
        "rating": None,
        "review": 'Making me rethink how I structure my programs.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.G6SRByFrwqob6KQdRTDbl81VKTwojNrO2p3dvKOrV5GcSAGfmbUPvSh-eLTWCJvvTm7LL1HLhkUJFZhwYLoWw-rFA4DLRjD-Rmsi1cPKmQ6Qxu5I3hVnvyIe3OVhObA-O2xQA0830rQXY_Bw44urBnjfU7aNhagvf9s--UkbqXHG2OobHz6-cU17R5XvGcdeGcOZ1SkSr9FuW9BGfqK-28ef9Wjp5jGQjY6fC8VfeAk.g3FlgPMkfl6BK1JiTqTa_eCMODjRC7azM9LU8y_W7MU&qid=1771696354&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/cleancode_c4vnwl',
    },
    {
        "title": 'Crime and Punishment',
        "author": 'Fyodor Dostoevsky',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Deep psychological exploration.',
        "date_finished": '2025-05-12',
        "purchase_link": 'https://www.amazon.com/Crime-Punishment-Fyodor-Dostoevsky/dp/B08MVSLVSG/ref=sr_1_1_sspa?crid=26AFLJI5ZT3OB&dib=eyJ2IjoiMSJ9.7qfe7THFz1zfhk9nmYbx7fGZSCybJmyrf9PdIvzq_gf0YddZ5DEmf_JpWkAHRP0rXLV6e0V_XRhcNzxmDU_D6NYOKo_CPwWVubqci5MzAMxMukB4ZAIlv_2xP4Mj1AXS2clwkia7xnvTJC6unsviwiCH1xO4-JcORN2aYq8Hueubxr0G-Lsc0EywnCeEPnhfnsOjkfn6wDt9qmXCdRZ3X34MjnBzDpmBrHkdkgmHCNYk-Mg5Cxq3xhNAaJxkPAGxMnMVXyzUzTxEfiBW7YO01kyaVnQa5LieQUabIWGu9jI.S_CIwYkqRl0PvbjNdMTqC6XA-HHmhFrnpxL6YDlZVvk&dib_tag=se&keywords=Crime+and+Punishment&qid=1771795800&s=books&sprefix=crime+and+punishment%2Cstripbooks%2C126&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/crimeand_tr060s',
    },
    {
        "title": 'Deep Work',
        "author": 'Cal Newport',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 3,
        "review": 'Reinforced the importance of focus.',
        "date_finished": '2025-01-28',
        "purchase_link": 'https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692/ref=tmm_hrd_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.-Big-X9XsMQ0-dzTEtcoh03hw1IIXUq9aaJ7l_7-PO5ofpB815x809hMSoc7gDVv1A0IVpOAYXYXA4l2Mg8gWFtwSW4CayXFUzVs3R49zd3KMxSa_ymDnA78VeHqEY0Xl6IrBd_v1ljBrr31lS6xFDb4z0Z5eBRlNmw2cTxzg72S9YGhvDu3LYZevLMqGMhoQnIx13ZnvzhTJUPsBLvmm43ppeWMMJj6WDA1673LyGc.QI8Ldu6q7wt0geCFs9UbBHUn3osX0Ox3j1ZH5O7ozaE&qid=1771697246&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/deepwork_jh3cbi',
    },
    {
        "title": 'Dune',
        "author": 'Frank Herbert',
        "genre": 'scifi',
        "status": 'currently_reading',
        "rating": None,
        "review": 'Dense but fascinating. The political complexity and world design are impressive. So far enjoying the read.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Dune-Penguin-Galaxy-Frank-Herbert/dp/0143111582/ref=tmm_hrd_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.zaZzED0zfaOD49lJ_-96hPjTtxbYkjKq0zah-cUlXjqqTBvXB9BGd4aQ67ZWDIvJlHJYoK4xfVRtzAIxSpGIUrz0tbEqbEMJfneIlgduOn6-yCSBPlpV1m1wjRmFv6mW_10z2tk_ZFZLvccUiAvJdckJoWhuv2jxm-7Oze8__7fqvZyMAJquwmGPXZe2TJLL3rgv0_4LEE5dp_UV8Lfazr1SNnMN9-t2hHoGYgwUlNE.27oKR2al3RJrwUOqCLiUMSX4R7EracDC69VNIb0zX4Q&qid=1771619371&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/dune_biwjsm',
    },
    {
        "title": 'Fahrenheit 451',
        "author": 'Ray Bradbury',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Short but impactful.',
        "date_finished": '2024-05-22',
        "purchase_link": 'https://www.amazon.com/Fahrenheit-451-Ray-Bradbury/dp/1451673310/ref=sr_1_1?crid=13MMRQXK146VC&dib=eyJ2IjoiMSJ9.-9ho4xRnzvCHdCT6Thu9aNaXw8XDy09HDVgYn32ZWwpqZD4Ar1kSDiSLK2CHjR5z4dxI5VxENHmkDI4O5zKNtYiF7LC8u1kS5FOUfZwx0TfBpoMb9hKvoewHAD1jcMD1sY9Xq15XSjDJIa4IN012x54vPBejtddtmnfCHxhHYBtBsSk4bI3_nFBZBgwlv4kYOorCEbiQ2tQ2nkANI37zzr5BayL7OpVCXvMnE7pIZmE.WhzyZ9w4gCo2M1xqRKEBe_bkCASdGAuozSuRr3aHqJ0&dib_tag=se&keywords=fahrenheit+451&qid=1771791943&s=books&sprefix=fahrenheit+451%2Cstripbooks%2C156&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/451_fw5asj',
    },
    {
        "title": 'Man’s Search for Meaning',
        "author": 'Viktor E. Frankl',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 5,
        "review": 'Powerful and perspective-shifting.',
        "date_finished": '2025-02-22',
        "purchase_link": 'https://www.amazon.com/Mans-Search-Meaning-Viktor-Frankl/dp/0807014273/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.phUc2adLzv8edJKcJfYGiYmYQA_wfSFAPr6oNqdjFnbKjiy95ci0EjAEVKg9W5EEPUlBE-U3hbH0FXQo96OZNmFcvG-CBDvbKjLmD2cv8RNzDqVj8NfT-Kz-Nbai2NmNXgcXTsIQG4KId9tWQQZu33cTHqT5b-sulCNGgJVd8NDA-2AQWNiSw_tKlnPiM3BEwGfppblIOCcU6HHTGYHMG2sQ_Tfc5nzC8anxLOAbrzU.taPs0KxHYddx9UL4b-2UCewZnP4x8PlsE_iHFE9MKGE&qid=1771728460&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/manssearch_d1vlyx',
    },
    {
        "title": 'Meditations',
        "author": 'Marcus Aurelius',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 5,
        "review": 'Timeless Stoic wisdom.',
        "date_finished": '2024-12-01',
        "purchase_link": 'https://www.amazon.com/Meditations-New-Translation-Marcus-Aurelius/dp/0812968255/ref=sr_1_4?crid=1DTK2M2KI9TZ6&dib=eyJ2IjoiMSJ9.w5dtuVMp407CdCRbqzzjyger25W3UElJikRDV0E39JsuimrT-J27Y0TBzyfafo1tBgfmZry6_L7tOQHX5Z4AZWs8VSEiSCfF6J_jO22PJIMTVS_f72HrRbDTk3msN1HcqC2mNC2kW9XHN9jlAtBPMALGLIYrUQgBPalWf6uV28szv4Eobxioi3NY7_tBSBj8uszxlg8-r_hPB_CAcxp8wgtPMfeytnuHbwUu8Ws0UY9OOucjRexbrgebdOdNpVqltlOyfSrqnZ2hIUdYxhS4www33Ma8mhCFVuzcSOjK6Ac.j4Ur5nDJ2sZJ-ku4GxIrSnSDgs6G3dmDbzBSEk9mZt4&dib_tag=se&keywords=meditations&qid=1771797107&s=books&sprefix=meditations%2Cstripbooks%2C143&sr=1-4',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/meditations_adbsho',
    },
    {
        "title": 'Neuromancer',
        "author": 'William Gibson',
        "genre": 'scifi',
        "status": 'finished',
        "rating": 4,
        "review": 'Cyberpunk classic.',
        "date_finished": '2024-11-19',
        "purchase_link": 'https://www.amazon.com/Neuromancer-William-Gibson/dp/0441007465/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.ArlChDCsKlOJy77lHBKtdqgVGLQyBiIWhiuMJDlV78xESyI075vm0p-LnTqPOutG-Bz5Xlsni9wU6m-mx703d7eXT248zHlgaZ5ueSft8MX-ounGM2g6KPRjDFW2Y3gyXJcOXlsGRKzlex1F87DFtMK_skLzWtcqG_-V8Kefvu0Aajxf8TX8btiWCe6E10c-9H-dW1l_lp7NOCzZtPkud5jIWcoeXit_3ycKcJOwAgs.Bf1nGlIwL9RPAyuOG6cKNW2D4aKvEtTIK_OP3iDM9WE&qid=1771796186&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/neuromancer_mqrgup',
    },
    {
        "title": 'Project Hail Mary',
        "author": 'Andy Weir',
        "genre": 'scifi',
        "status": 'finished',
        "rating": 5,
        "review": 'Funny, clever, and scientifically engaging.',
        "date_finished": '2025-05-19',
        "purchase_link": 'https://www.amazon.com/Project-Hail-Mary-Andy-Weir/dp/0593135202',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/projecthailmary_rnytxm',
    },
    {
        "title": 'Ready Player One',
        "author": 'Ernest Cline',
        "genre": 'scifi',
        "status": 'finished',
        "rating": 4,
        "review": 'Fun nostalgia ride.',
        "date_finished": '2024-12-28',
        "purchase_link": 'https://www.amazon.com/Ready-Player-One-Ernest-Cline/dp/0307887448/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.TWZH9aofRtizAYNJpDzl2E3ibHkZ_GiaYhm1HgNdBMcJkTI3zeCN6aGQ7XOppO5Wmy0hNmhYjqt25YoOR3SqgGv_aFZFFlPwc-EMLw-xxT0vAmTSgk2T6U4oGB8YVA-lJsHjxT0Cn3TOxYMfbWBeEreJZSD5c6Kz_ZsNK6mepRh6GdaREkGCmBN5QZ-xGp9uMhWdWkaVPao9it7LFFHTCLTC8Ktn3bfVHNS0EQmEVEs.jC2abTpIw4Tjw6RZsmQXDQbFfwj9kqdWPbziePt4PBk&qid=1771727641&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/readyplayerone_vvmsvd',
    },
    {
        "title": 'Rich Dad Poor Dad',
        "author": 'Robert Kiyosaki',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 3,
        "review": 'Motivational, but somewhat repetitive.',
        "date_finished": '2024-06-30',
        "purchase_link": 'https://www.amazon.com/Rich-Dad-Poor-Teach-Middle/dp/1612681123/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.eQPStrjGba6sz60ZxfmUgZwcHsQmPLzMiKD-iHfkXeTl5n1vAlp_rY90P_NmxaRa-iipd6bALMMd8a2Qv4Khe00Hvcwv91uPHoLFPVwIf0PQSxFWnbvYeXox2ichO27DW1czcMv5SYGzZIAce87TH4Q0_EHhDkYQZDs2QsdM1XkC-faoJvKg-uDPEsZY4zbpO-4iKe6I4v4wDOTyOrTJzu0WEGQxwCBk2NV0xAR0eMo.XqNiyhA7JBXQZPCEA6cd8RFxkffIx3RJzmFoGJ5pG2g&qid=1771796460&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/richdadpoordad_wptyey',
    },
    {
        "title": 'Sapiens',
        "author": 'Yuval Noah Harari',
        "genre": 'history',
        "status": 'finished',
        "rating": 4,
        "review": 'Big ideas about humanity. Thought-provoking and bold.',
        "date_finished": '2024-12-12',
        "purchase_link": 'https://www.amazon.com/Sapiens-Tenth-Anniversary-Ed-Humankind/dp/006342200X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.i_RCehp6kCFmOupnplIMR0cZRY9XkXNN0VTDr5q2ftN7YrxOD7cnknK44Ij_vLrXKq_FOXu1qIq-ysxAWuBmWQrk3VQCAfetzzDGf4CrFE-EP2CqeMNKMd-LLG5vTd5l624YTnJBPe0i3XzqP9f02EXww0tj_EzhWviW_rcKayy6zirzkez87g_2PQhqaZiKcxzZitMHL3unpKf4-SRtBsbz_iGcvZtAp1389DI8CG4.9geeGhMLWXyDjhLs2C8e62aCPki9mpHDTBNcMwtVIO8&qid=1771696596&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/sapiens_wb4ttx',
    },
    {
        "title": 'Slaughterhouse-Five',
        "author": 'Kurt Vonnegut',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": '',
        "date_finished": '2024-11-26',
        "purchase_link": 'https://www.amazon.com/Slaughterhouse-Five-Novel-Modern-Library-Novels/dp/0385333846/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.4-6s8Gg6jGNZDqhjIk2ULCarUgsbPi1QVWvrEn7l8AZ5hUWsWQ-4jv4krNtTN9_Ji0kdbtpa4qlKWEd-52KTw0WewEvInJIHhd1r-JIlHAMg6uRYFyjDVhl6JBxXEbcCWQe-RtyeLaNSWaU_hOzG83mRhkeJEwWOFPBI-dSnufJ8JMjGlvvf_167KKg4scGG3d17I082m_IReLb2kfWOWPhRrSYu1sSiBMudV3BadNA.83GAtWps6aMxSELH9uvcLhQINMLCO8m8XyECoV5hoPA&qid=1771797550&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/slaughterhousefive_zluwvn',
    },
    {
        "title": 'Steve Jobs',
        "author": 'Walter Isaacson',
        "genre": 'biography',
        "status": 'finished',
        "rating": 5,
        "review": 'Amazing insight into one of the people who contributed to revolutionizing technology as we know it. ',
        "date_finished": '2024-08-01',
        "purchase_link": 'https://www.amazon.com/Steve-Jobs-Walter-Isaacson/dp/1982176865/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9._9KYdfWjGcMxZ79gkPmJOY8D_hjBZBZR-H8PGblN5aSKV1qlWNNVU9aLzJMdSWlAU3YKylISeVyvV70W4UXnzrv2Ccq2ZRKNnVCtQ4FK-8frHC2bx5jm-U1azCS0GMA-G9mCH3HnYA8tqb-yLgy3HvJas6PJ0-402G7zuOHADe4gDI-3fcvnN3To8VqT3cNIDDEJmVtA-r8nZJHHyeWLkzICnlDpRrvWTyuA_s0SJ7Q.r5G5QN0rygxs4R7KE7l1KaWuR2II9kqzCC1qdd84_H8&qid=1771797892&sr=1-2',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/stevejobs_bsqbbb',
    },
    {
        "title": 'The 7 Habits of Highly Effective People',
        "author": 'Stephen R. Covey',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 4,
        "review": 'Classic framework for personal growth.',
        "date_finished": '2024-10-30',
        "purchase_link": 'https://www.amazon.com/Habits-Highly-Effective-People-Powerful/dp/1982137274/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.SqwOwJ5zN4dTSawslkpGL3HNdNsaU4DRSacbUhSuOe8wb7aGMuW-uiZqaN-sJvD6I6lpZ74wU_dZwfupUCpxh_Xp25ASJmpuZc6DTysiuio0mo6DjgSlYXXu20jQlTn8ukCrQE5BS0RN-sFFOKzEECnMMBdJzW6gZDU88kKi39oY889c8Pft9nlgyRUGFws6KVJ6Jk2uWmYqITXarGa26Nm9jSiEXG0CB5MaOotLPqg._hYMhHPxqSUrpxT5lvSWu4pyZbv1ue0nyM8pzIFbC8A&qid=1771697646&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/7habits_tnvk0d',
    },
    {
        "title": 'The Alchemist',
        "author": 'Paulo Coelho',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Inspirational',
        "date_finished": '2024-08-17',
        "purchase_link": 'https://www.amazon.com/Alchemist-Spiritual-Self-Discovery-Novel_Get-Captivating/dp/0062315005',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/thealchemist_gmofn6',
    },
    {
        "title": 'The Art of War',
        "author": 'Sun Tzu',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Strategic wisdom that still applies today.',
        "date_finished": '2024-01-15',
        "purchase_link": 'https://www.amazon.com/Art-War-Sun-Tzu/dp/938091489X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.f4k0xkbcKYrEWE-uoMnAEiMujVO1qqu-mLxSNTMgQCfSny7bo5aUQlsCBnUWwGqKR2Wk88pDGdfTuopU-OwRuQg26xoMQMsykcRPO8XqvMGdXPfsoVv6pmEekHOavcPOMxo3j1mGm2rPBspTlq_CJfO-V1YDoEbpERW_tm0Q6mcjOHgQK9QpRTvPule6te6s6g53NFIKTbBScVC86O9nfeXsq0635zAD2Nbkziwkb4o.1DEMkDSvhmLz4LWSmYTDlLS0UKGPuVzfCx4aMoMFTw4&qid=1771795924&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/artofwar_doqlsl',
    },
    {
        "title": 'The Book Thief',
        "author": 'Markus Zusak',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Emotional and beautifully narrated.',
        "date_finished": '2025-06-01',
        "purchase_link": 'https://www.amazon.com/Book-Thief-Markus-Zusak/dp/0375842209/ref=sr_1_1?crid=16OB7QKNXPL34&dib=eyJ2IjoiMSJ9.sNHYohCJz4YRpTnZx5qbzBys4_AgHeYROMjhXIpb1Bq7zXRRB8Xn7A4PhSZt8SkOhvWPC5UXvi2wD6wyOYVZpvweqJKwamZNi1xUgHskYDcJ0NfTY_zcJM2-B3HFpxmWwsiaBIdN2a_ACsNzI5ceye7VfOnHy4XaMhsDNwwDyV8wQdP4Y8KFIebwApS2iCVEGO1Jlpv_i0QPBnd23BPm6aeCLVSN3s678VHlaDTeZL8.JBQiVMAeq4rCSZtILZbhKYx5lLLeYBEy_1VysTln7iE&dib_tag=se&keywords=the+book+thief&qid=1771794448&s=books&sprefix=the+book+thief%2Cstripbooks%2C139&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/bookthief_bqgrxu',
    },
    {
        "title": 'The Catcher in the Rye',
        "author": 'J.D. Salinger',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 2,
        "review": 'Interesting book, but not my favorite.',
        "date_finished": '2024-04-09',
        "purchase_link": 'https://www.amazon.com/Catcher-Rye-J-D-Salinger/dp/0316769177/ref=sr_1_1?crid=3ENW0ATX45PCS&dib=eyJ2IjoiMSJ9.6FcPNdOPTUNayUPzju58dFLG2FzEvrufA0siKUPoRr4YXIbCEa6ZUNqoq0Tf5OQj-WrOwKGVcQe2fiWl6-Gvpi5Oa46hhLY_e2-shFiPAoefoLE_cdgkJpXncqak2RHBpNDc92_wmLJg_ZC08BqaXZc-FEntCXFqss1w79quY30NhLW3f6vgfxlQvBuL8tDFk49RfGZrr5SoxpCkpamA2xKFtrqjugPxSn0jh-VvQN0.Jsi0zoIMqaqof_FXsDjMQCBkCq51hJebCuUh4IssNoI&dib_tag=se&keywords=the+catcher+in+the+rye&qid=1771794219&s=books&sprefix=the+catcher%2Cstripbooks%2C148&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/catcherinrye_kevxnw',
    },
    {
        "title": 'The Code Book',
        "author": 'Simon Singh',
        "genre": 'history',
        "status": 'finished',
        "rating": 4,
        "review": 'Fascinating look at cryptography.',
        "date_finished": '2025-01-17',
        "purchase_link": 'https://www.amazon.com/Code-Book-Science-Secrecy-Cryptography/dp/0385495323/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.49OS7u8hjAIgIEzFU5VCmWdIbwBXZlWC0Dt3Y1Tp8fZbBWHnNgd99rkxOnA8e5bYAf3VaYZX-AEizpfA9HvHW7n0D2DJ6UCLN8D1WQmOzgi-R7tomz0JC5FPyjKBF7Rmwl_fi1AxHzp-GxZFIn_PH4nXUzLADW07vOTWXUklvHFaThcj0PKyTI1u8-Gh40m_zGaSrd3OUpMmwL1FyOCNJO2_ZoYS1Bj-Us0Tv2VJGsM.EpZ9CpaSA4cjem4BGiO-6CGzpzUAL437WK2QA6y9JPk&qid=1771797367&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/codebook_mtkkok',
    },
    {
        "title": 'The Da Vinci Code',
        "author": 'Dan Brown',
        "genre": 'mystery',
        "status": 'finished',
        "rating": 3,
        "review": 'Entertaining',
        "date_finished": '2024-05-03',
        "purchase_link": 'https://www.amazon.com/Vinci-Code-Robert-Langdon/dp/0307277674/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.bZpcS2XfRwPeRcGjjsRxS2Qt2LZBF_v1Bsfyb0V1K5oSA4xi_VX6qz3fOrWtE8WNPXYluYBm7lZ3f0kWnuloBQ4naAzXh-YlkCg9c30k8DOb8-ympe4-AcTInxyUdixKdbCBteuRevYR27F_ST7YqkJRffrJ86T0ogdgPVrW0j8LZG6rZoTeTAjHyQKIshxpODZ8XaezMTh_ZgOrMRUycFJ_lz28RC5y1HXu5xijRAE.vzpzrdvIzjKauQ1cHDw1qoDZh1yD4cj6IHQ5nWGvotM&qid=1771797441&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/davincicode_ajpfft',
    },
    {
        "title": 'The Fellowship of the Ring',
        "author": 'J.R.R. Tolkien',
        "genre": 'fantasy',
        "status": 'finished',
        "rating": 5,
        "review": 'Epic beginning to an unforgettable trilogy.',
        "date_finished": '2025-06-15',
        "purchase_link": 'https://www.amazon.com/Fellowship-Ring-Being-First-Rings/dp/0547928211/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.ghiFsDXAHnqwzgSlMK7574GQESyQQ01k_nzqXYwNfgRdEGgL9sJoyE3tH0WVN3Tln9R4vfdZoCjZfmn9CzUFrSwTd2DC4vkEqsJdgy87I-OXX0hMHYDPr1Z9jgJeB2rNnom3dbYzMCIa9OyM7o2E1Xm9ez1O9WYE_HwryNjU49MfGQK4_O8Q98-fxvK2tEZMtf6Q8SJopIYcukuKMSejFzAPUhtEMgUKbzwWR7binKeIQxRrPLCqY4KxkPZ2pLEd0CK42T3Lr6m7HwUvyr27qUTPfZ8jLkcmgbwJ7lxogvw.V65C9C3nSqYsm_cbQ9FURc4uLOsQxip7sLaKu_WoLiU&qid=1771796567&sr=1-3',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/fellowship_opjsws',
    },
    {
        "title": 'The Four Agreements',
        "author": 'Don Miguel Ruiz',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 4,
        "review": 'Simple but powerful principles.',
        "date_finished": '2025-02-04',
        "purchase_link": 'https://www.amazon.com/Four-Agreements-Practical-Personal-Freedom/dp/1878424319/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.L-x8uSbCENVCVyajat5EpW2sXhe9cgQF65TQA5971TWIKTWreEf8-pj5ToOdO8qB7ijv4pYYfzB6GKq8HizcSkLihKUDs74KwFZIndIF0rCblI1rlErlZmnv3qePFkox-cpZE_4nFf1S5wCkZKwyAPZELMcfagzZ_ZDZr7ZMHquaIXFqJTgWOGnr8Hi4D2sgZbWzNrj-SiOaDg3GCIIEXgFABtMPcpTz4urk6fX8bZI.07FgINSgrfcSQuR1NH6PLkoEHbQP9gx75Wv0bxbQou8&qid=1771796027&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/fouragreements_ak3l9h',
    },
    {
        "title": 'The Girl with the Dragon Tattoo',
        "author": 'Stieg Larsson',
        "genre": 'mystery',
        "status": 'want_to_read',
        "rating": None,
        "review": '',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Girl-Dragon-Tattoo-Millennium/dp/0307454541/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.AA51RLOvcdbfsKKDYgiSvi8fqMDMtFUi8SgvR2Yfqy54JYXYEGEl4_M7E1NdzZ9dNIy6wMuQKTGwqq1xHmIhM3xy3LTxGd1s5xBC0NnDY3BzGw76kdmu_ZusWnVRMnwtJD3WuS7e99ehdilmP1khxonwAmf1gAZw-i1FqO3sLwmC-Pmt33PfuKrOqp9yvjiPioa_5G9HyKrtko5Z8opn2Thb1l0bVTvbY2NSCW4anVnRiiAFNUSObpcIdzxRcJLoPsjUep4NA7mHnI8CQoUwOVSbLagC7U9bHZY4cWfi2Rs.4Ly636boI-9iiv12JyNPKZPp_s6O69tUCCJSj03ipZA&qid=1771726698&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/girlwithdragontatoo_hozm0l',
    },
    {
        "title": 'The Great Gatsby',
        "author": 'F. Scott Fitzgerald',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Beautifully written critique of wealth and illusion.',
        "date_finished": '2024-02-27',
        "purchase_link": 'https://www.amazon.com/Great-Gatsby-Readers-Library-Classic/dp/1954839243/ref=sr_1_1_sspa?crid=2R2JNYUHPX73&dib=eyJ2IjoiMSJ9.h8xnMEDrBwH2Yd7qIMeYMucHt_fdCBKTtlBYd_RMPzvK2DgmWpSgPiWPDugy9-ToQ7cYs-GfA81I1Y2vr_1dVInSpQyhE2elqAysbkIQ9G1U72zYLa0GzRlhgZ9wK-JuD3JKwneziP_mgekCVVcuKGS3Yd-oIAZ4tuTw2ST7dq8B4Po8q2MS1KSN9K5qk-S06X1GeITrMPoA4PTIf_QUK1zVVohy9pt9xhjOgO0-1fA.7dLKOAEqbA15iF0SFEn0WL_KaByI9Wb-WuE0ShO0mVc&dib_tag=se&keywords=The+Great+Gatsby&qid=1771795548&s=books&sprefix=the+great+gatsby%2Cstripbooks%2C173&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/greatgatsby_hhrytp',
    },
    {
        "title": 'The Hitchhiker’s Guide to the Galaxy',
        "author": 'Douglas Adams',
        "genre": 'scifi',
        "status": 'finished',
        "rating": 5,
        "review": 'Clever and absurd in the best way.',
        "date_finished": '2025-03-01',
        "purchase_link": 'https://www.amazon.com/Hitchhikers-Guide-Galaxy-Douglas-Adams/dp/0345418913/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.T9qfV-1KgRGkm_g-HFJrh8hxDdVja4HG7biiQCA7CDcEt1vf6GgMCA8ytmUAOShvCkC7pcPHp4JfwkawnKsdC5ig94TqmE95UsDgpadoXRhHZ4Y-8gUWbRo-jtR3baq1rMycBvYehwqUlC786trmtrkYiNI390INxkJhscspuZSgc15iJclR8tcvu55u-LS52y5JUCFdPJC6ax1LL4mOfHpZ8evkAPHt_ZGlBi0ge1A.N3mDPmPnvJWyy4k2ZTnPd9gtZHwE9d_QP7-vgrz9da4&qid=1771797009&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/hitchhikers_qwaktw',
    },
    {
        "title": 'The Hobbit',
        "author": 'J.R.R. Tolkien',
        "genre": 'fantasy',
        "status": 'finished',
        "rating": 4,
        "review": 'A charming adventure with rich world-building. Slower than modern fantasy, but timeless.',
        "date_finished": '2024-11-03',
        "purchase_link": 'https://www.amazon.com/Hobbit-J-R-Tolkien/dp/054792822X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.x4sNkHfcHq3kdN12k4mD54JOLePFeU9hJtM31xLmVRbyb77AzZJqoYyzhisBOsWCd7sKUe5OYp3xiRKRQKpbY7Amn5V8klzzyZgJbT68Uku8cfWpAcQwcRGKrYgFnLULkI06umVpndWLm00pZ5xhEGml1gkbNGcTwCT6H2zGr8XnmPIJO9rzoVTYMz2pLuD6AY7X0Dt3MIHIlcAZAZvuhpElotVZgesY2HS4K8zLGcctwhG2Fv5VKQrsuSSIR0eAaQjsGfpm9ksi0zdendCJ2D23ERr8aO6Xtd9XChlS6Uk.p4DtyN6RXw3bU3uFRho9GNeb6GnCaYeJwhEaLmngZbQ&qid=1771619264&sr=8-4',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/thehobbit_cxjbcw',
    },
    {
        "title": 'The Hunger Games',
        "author": 'Suzanne Collins',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Fast-paced and gripping.',
        "date_finished": '2024-10-08',
        "purchase_link": 'https://www.amazon.com/Hunger-Games-Book-1/dp/0439023521/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.wRGe2_nA6GtqHIe_79adOkmdbUeoZy2A8vzehonIFBOyptqi1y5L2msxwTziV7RN35mK8l5vTItWKdsZ0d8edUxZY0b-p5uRewTm7OSAovc5k_4Ljehs6i8k9nmS8yW3Vo6p9ngglPA5J31JL35S3io9HG7mWwa0aSBvm30QdfOpvruaY3mEa_Yo0R-6mULh1zk2eQpKPwU1gX9paM4VJupHG2jud5PxXOLlSG_AIxw.Jz_AjrDVt8UsHhBB5r993L9S09-_d8NF6yPVQ2y3utM&qid=1771797258&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/hungergames_prq1dp',
    },
    {
        "title": 'The Innovators',
        "author": 'Walter Isaacson',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Great overview of tech pioneers.',
        "date_finished": '2025-02-27',
        "purchase_link": 'https://www.amazon.com/Innovators-Hackers-Geniuses-Created-Revolution/dp/1476708703/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.lkLGxjD8LlHYt4XySsg7L9OovAiqbvXUSpTwVFn0DRrHz_d6tFp31SEScbrEL5NX-ZafTKn5XYCf3eliWomSINHGOVojzuoB0PFG31J2wfxF_ccZkO2tqLeKVoTC_i6qDdHSZmYg78H7zi0ETrPYyBy9rSP7iO7_4ANh7VzSbjkTxZZSeNUD6eB8tEJej38y1BeIApsNG3gjwvE5I7LeKhRR0G9sGO6f4FqupOAD46E.Yl4uXMeVO9zr-RWxgvDgMftGTwIdr7R4XiqXo1RufCI&qid=1771797797&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/theinnovators_k3baty',
    },
    {
        "title": 'The Lean Startup',
        "author": 'Eric Ries',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Great framework for building products.',
        "date_finished": '2025-04-18',
        "purchase_link": 'https://www.amazon.com/Lean-Startup-Eric-Ries-author/dp/1524762407/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.FWUsaeYmkwVyAYKkatWi4eAC5FZvDXpssyX5S-Z1X1Zk2PAphyRa5hSn0h2QMnzx3X8MPt-zUFlzPUHUIUhjTqpWOboHLEtSaegNGTraZSOhrZOjHdVr4yNaqXvUpUpppLJrZRJKe_7cdr02pcXy8eoxdyrUHAWDR-bd--d20rXlrXnmrrjmsktRe2c3hQF-hPlhMk7prTyVyYfONx6JB4GquptSe3QOkOEAOt0-JSk.ty1KBHDE62dGCnkgChsrcEpMSKsnPyZJfrm-rzwy2l0&qid=1771794308&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/leanstartup_is9dzj',
    },
    {
        "title": 'The Martian',
        "author": 'Andy Weir',
        "genre": 'scifi',
        "status": 'finished',
        "rating": 5,
        "review": 'Smart, intense, and surprisingly funny.',
        "date_finished": '2025-06-08',
        "purchase_link": 'https://www.amazon.com/Martian-Andy-Weir/dp/0553418025/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.OYbpaOdbYLbIP2rRMMV5pcdbu9Dm7MIVwyGYsu7uMqPSwkzrK5fHPLv9H50MHhMYRrua8qeBhWN9W8aRbeA0Xhmula0a2B_c2IfGgazdn2pA4vJaRSpcWVEeP47zOrj4TCpuJtgYpTria4LTWltufH3ojm8f8YDn7CmVLrh4Emh9T0Cc9BFt2nKKdTXnUV12u27-V7_x3bu9Qy7B4JgXlYtLlYXsU2YjcovFR8AZn8Q.Cxoie1rsqS7AaGjtvHVP8oheIFWyGCo4ePue9fqD0p0&qid=1771697735&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/themartian_qq46ur',
    },
    {
        "title": 'The Midnight Library',
        "author": 'Matt Haig',
        "genre": 'fiction',
        "status": 'want_to_read',
        "rating": None,
        "review": 'Excited for the philosophical angle.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Midnight-Library-Novel-Matt-Haig/dp/0525559493/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.4bAVg9aEhSz4de0SEMuAuRPD9CnhLSZgX3IM25mk9m2K0_HCF6ItVfXPiKMCLhg_8ZYeK38G0VtG2y2pJBEWk5pc7miLpaF8d6CCeJQvT_ibZDDGhIztWTbcvGfjkHTjJ3wJ6OSPQEjZnNcbtIbzP_UOf_SRqzGOIRh1nC4tQY5SpS2VpWf3T3Qe2BYsuH8JgaJC0oQlxLn3SpgLO_fwLNNg5uSdHJk7tWrwGyPBTp8.fkeaN4N0gt2yobA7U4JaL_xLkGyKaM67NWEDMm2nNu4&qid=1771697467&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/themidnightlibrary_zwq38l',
    },
    {
        "title": 'The Name of the Wind',
        "author": 'Patrick Rothfuss',
        "genre": 'fantasy',
        "status": 'finished',
        "rating": 5,
        "review": 'Beautiful prose and compelling storytelling.',
        "date_finished": '2025-04-02',
        "purchase_link": 'https://www.amazon.com/Name-Wind-Kingkiller-Chronicles-Day/dp/0756405890/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.5sEZ4ifw46n1WdZPZEeuEZSmCj16NNrR3wozYVVCAH_M6lL4czFJT9wciOpTZUmQgvx0P5W_1qrmTa6jNhGkWtegXqgf05wLZTarFfRkjwccBiz4c0tj6Iq8qY3w8wQnLBnAkAdfPhcQaBy7qRImqtbxHCpXOjrDP-JKMPFLCp17rVYmgVjgd-d_OwV_DawYeJnkhH9Nab0DchVMWBDln6jWiDc6VYgNOgG-kCurv6A._QY9pv7k7JGhLTBLRb4I84Iu8RCqGqwA_ismhuEyvD8&qid=1771696748&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/nameofwind_oksm2q',
    },
    {
        "title": 'The Night Circus',
        "author": 'Erin Morgenstern',
        "genre": 'fantasy',
        "status": 'want_to_read',
        "rating": None,
        "review": 'Heard it’s beautifully written.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Night-Circus-Erin-Morgenstern-ebook/dp/B004J4WKTW/ref=sr_1_1?crid=3M0X1XHLFWE1H&dib=eyJ2IjoiMSJ9.IhJYVZ99LOlEubYo3BPu3jaWwGtLyQorlZMt4OO4evOX7nPQMS0EU-CgBzJqiACPtuRECfMZwtZQXA6MLFoPsaamgszQf0DWgzJJterFBMHDEnV30D1FxxwVwzJ_mQ3OvfNzKAXN2M0fU6QKEPlzqTRmaMJprxY_JAfU9pJyc07rhFvJOgftfFmRPd-dZUfs6XbQEocTSXCBUsn0QogMb8J0jUZeyJw8PeYnvPgShoU.FmvtADtHnsHX6_Ih9u-49puXwwnyYX6ih3FoAQlgcIA&dib_tag=se&keywords=The+Night+Circus&qid=1771797192&s=books&sprefix=the+night+circus%2Cstripbooks%2C120&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/nightcircus_idwvsd',
    },
    {
        "title": 'The Outsiders',
        "author": 'S.E. Hinton',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Emotional coming-of-age story.',
        "date_finished": '2024-08-01',
        "purchase_link": 'https://www.amazon.com/Outsiders-S-Hinton/dp/014240733X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.ecVbD975T91ACNzNklQPmk1na2YM49c8StzuyADoz_aB8WOTgyi1qLjiKiHruwx3GLwBEJzsmarb_lczkvNwuhgHvSwT3hazcjlWsimftN8AMmm8odoN03GY24yyXopDk7fBji_6BiafAcmgbAnPqUAOvcFx6s1rTxrJhEoCgDXs90eoJADYvUrjig7mKQmuNgdNCtevM-VXMsN1wx4IXgT2OC-36w4iAAXfzzYFcuk.npYD31zmBMnEkn7-DM3m6vjKgYu-bdRZDUuMTmX1rcw&qid=1771796331&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/outsiders_bochuv',
    },
    {
        "title": 'The Power of Habit',
        "author": 'Charles Duhigg',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 4,
        "review": 'Interesting science behind routines.',
        "date_finished": '2024-06-19',
        "purchase_link": 'https://www.amazon.com/Power-Habit-What-Life-Business/dp/081298160X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.MORBLkX8SpDWcGGhHUAILRGjVPoYBvbw3xdnMxK73cdb8QxRCKqTw6EWPoW3Y2N8GRg46gqDspI6aEqu1YvLfXyehhXda4vRuLVjPjsCPvj9rMfUfblrso6QnP_bDtjDC6mW4Tcgy4w9sCvnvIVkNdBOw2YXO1htLwuN_idZRH0hOUBnvP88S7j6AmtAbfdjZ0rMV9CQQOknRmBF-kjvNV_NmXtHSmbvmCQ6QCylieg.vdTJo2oOOPCpg3NpNcQZ4wX2q0Olq-GU7u_V0KZng_w&qid=1771730051&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/powerofhabit_uhy3xw',
    },
    {
        "title": 'The Pragmatic Programmer',
        "author": 'Andrew Hunt',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Timeless advice for software developers.',
        "date_finished": '2025-01-05',
        "purchase_link": 'https://www.amazon.com/Pragmatic-Programmer-journey-mastery-Anniversary/dp/0135957052/ref=tmm_hrd_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.zz9H2TJzEAmlKCCtRp1vfBO6zvqn1L3mG3Ry6lzfpQ4hOcRLY6Z68JPeupvRUZkg8Uo6Db3drOjj96XrhnibhFydc21NkwpvHHMbkcQDvkHe8TdwX-aAAcKsZ7gGxRu0HZhg9TenqBs70gxLgMIe_tPxdbBjWoXEvNbii1-VvE9QQxME8qCofOfNBHM9Q9RKMMUhO1Y0WZvrAsQp-fEudNei3-q8VM5P5VOZgz-EX98.q2b7NmQBwyza3oY2d1F4UVA8QMdDI-ZsqPRFDjYJB_Y&qid=1771791733&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/pragmaticprogrammer_kjzba6',
    },
    {
        "title": 'The Psychology of Money',
        "author": 'Morgan Housel',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 5,
        "review": 'Great perspective on how behavior affects financial decisions. Very insightful.',
        "date_finished": '2025-02-10',
        "purchase_link": 'https://www.amazon.com/Psychology-Money-Timeless-lessons-happiness/dp/0857197681/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.1Ej9TpPoVuWM_km1joB3iuaKjJP7VmfHDPiAAp34OYAD8_XRDGfrvMxG3HmgBrvhPop7RzBMJpyVVdihpyHNi6n0EV2FaHq440BhNTOpruWS9aCCJ075H2t53m1H62nMjcwvNDdDl4I0JKveiVohjusbjX0EKzeebkalhvVVrgPOAP8oxa-duejz-GbBVK5wtpAErjhazuna0zQiwHh16Wqmmy6Dtcbee6dUt3SbZO0.TRn3pCzg86ZKQj_zzO1EHh5UNl5H3heagBxXutNQLR0&qid=1771619605&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/pyschofmoney_roeprh',
    },
    {
        "title": 'The Road',
        "author": 'Cormac McCarthy',
        "genre": 'fiction',
        "status": 'finished',
        "rating": 5,
        "review": 'Dark, emotional, and beautifully written.',
        "date_finished": '2025-03-29',
        "purchase_link": 'https://www.amazon.com/Road-Cormac-McCarthy/dp/0307387895/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.y0Q3cbIXemE-WMyF25UOQRAUVqgp6ndpatPSamS6oD-_VSg-TfT2rx9YPwzyBIovm5ydBEP_M_qPPvoFNQhH_l6BKL6oNLf2WjtWSh7m79xrphDmQQDp_fvwZTtSek4OrQ_wh_9Tidef-LcfzH7iCpWWNVnlxzPDanTtfGCxQD1vk8tEDYu573HArz3Dx8jVUm5Nswn3bAAhV7saQzMm1fThhND6d_B5sFdreYCWU18.GVL4XQVSKmyEeouxQE2xfLgfhI2TM0CICRvzPzUkfOM&qid=1771791552&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/theroad_cij80o',
    },
    {
        "title": 'The Shining',
        "author": 'Stephen King',
        "genre": 'thriller',
        "status": 'finished',
        "rating": 4,
        "review": 'Creepy atmosphere and psychological tension.',
        "date_finished": '2025-04-25',
        "purchase_link": 'https://www.amazon.com/Shining-Stephen-King/dp/0345806786/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.H5bj46hZSWxAeBIzJWjGlbvTAFl8b24FeJxIqrMfAIFrlLQfsMCUYQHCMQmOZgYhR5NXJ1h-bXRnGRxa5LPqam-R1ZDVs2rSed5f_85OcXoPgIY04I0jTnA_EVJBT24FIfdm5uQ762cb2ADLjT2L0cC7uB_jqYY9FkaTol_Rgy_fuUVZVLiTAL8yG9WdsmkYlV8VMOVSZfE-JZ2J9zlnnrjXMOk9uBGjfk9BxM7saFk.gfdM3GnrLDVjKlROaEn7wMjc6JqH4sUw1Aa5uoBJBNs&qid=1771796670&sr=1-2',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/shining_digkd2',
    },
    {
        "title": 'The Silent Patient',
        "author": 'Alex Michaelides',
        "genre": 'thriller',
        "status": 'finished',
        "rating": 4,
        "review": 'Great twist. Quick read and hard to put down.',
        "date_finished": '2025-03-05',
        "purchase_link": 'https://www.amazon.com/Silent-Patient-Alex-Michaelides/dp/125030170X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.RkvX9My_1hiBU_c8TbqGL1eOMAduqrtdabDNL3AThgMiV8MyX_xawTNb91W4O2Qt5dPCsJHisO02z956RAycvbCPaLlu-IX8U_BhY4Yp7qWsvylDV9BXiAlMmew0dgPdEBNUbUOmFPYUhoXMu-I2RyRmrIxl6byhlNDLclntyR8KNx0gp2HvvHl-EcHu7x80IJhOwDIHv896papLOvJ_sVUUU1-jqXgEKwIt6SwJbz4.ENn_8GwBaXHaJTxUzMj5pSSIBlzevhxoMCor89RPnYk&qid=1771696124&sr=8-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/silentpatient_mvbiyi',
    },
    {
        "title": 'The Subtle Art of Not Giving a F*ck',
        "author": 'Mark Manson',
        "genre": 'selfhelp',
        "status": 'finished',
        "rating": 3,
        "review": 'Direct and blunt. Some good reminders.',
        "date_finished": '2024-07-11',
        "purchase_link": 'https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/0062457721/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.P4CSCe8y-TOpOgHpGNGbtSqpYajrcnKmNh4WtpTGrRnTdrHA2tQXM-GsvDctarA_5abKpVBX10x5ZC7n-Q4B3hlTyXEYTjt_nRPQzmzV22anUJEl-XSEW-E5WlJjGkQhYR-A4JnYCyGSa6-A5vhf9_za7NfYs3gQLCuUpHcgNOGCqiD9KgRFGsueMe7dNccBnKJpTmlPgH82XaG4T-AXeBfQ7ZkVR7HSl0V900kuv5w.HXQf-CezIvtasxkMVLVrjkN4lsOeezq5onP0wm95xV0&qid=1771698002&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/subtle_yp8wcu',
    },
    {
        "title": 'The War of Art',
        "author": 'Steven Pressfield',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 4,
        "review": 'Helped me fight procrastination.',
        "date_finished": '2024-09-05',
        "purchase_link": 'https://www.amazon.com/War-Art-Through-Creative-Battles/dp/1936891026/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.lgZ11asrWu6SED87cPivWyRg3WV74-logcj7-SwQYYcgpxOqXzY4OJkluthv6ZuF9SK9R_wL-rqoUuE_bCPJBFfZJqPakYc8gddVxYHDpcmsy1WzwNJRzHZl3MDscAHyl0oCCmnMsQK6givVPC3LsmjdDFv6d9REPNVkfQpc3UlPAfeSBEHuw99z4mqMhtWxuJPkMmKgC3iXU7tbivNkd9Mb37HiW4B3spiizbx1KF0.2lFzaKw0XhV5qzwkW54NAGVRoYrwsoW5uGn-qysiSb0&qid=1771796875&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/warofart_zaksva',
    },
    {
        "title": 'The Way of Kings',
        "author": 'Brandon Sanderson',
        "genre": 'fantasy',
        "status": 'want_to_read',
        "rating": None,
        "review": 'Excited to dive into this massive fantasy world.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Way-Kings-Book-Stormlight-Archive/dp/0765376679/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.R5qgtnrJNBLTi6X_OzNCncuwc3O5qKiddFhHrAKyiM5ZY5SXNwRXUXAzRQsqJW_3GoUAfEAG46z3siKsaoeY_TgqLZ7cjjuMbLX2HS73zCw0x-Vmj5k7PWmyYGePTVmgc8DJDwpYmSiOgjal5bHQpd7iEa5KmdPaVdT194uHT4dJXDzam34vrLAbPNJMCf6iO0QXgGDiZTCe-J--OdO5jWPFhjDEmqVxG3lqdF_bqSc.WnZUusJ3HkYqffDp1UpNessvlwjVmbIhRiUDnkw9Y9I&qid=1771794725&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/wayofkings_asn1uz',
    },
    {
        "title": 'The Winds of Winter',
        "author": 'George R.R. Martin',
        "genre": 'fantasy',
        "status": 'want_to_read',
        "rating": None,
        "review": 'Waiting patiently… someday.',
        "date_finished": None,
        "purchase_link": None,
        "image_url": None,
    },
    {
        "title": 'Thinking, Fast and Slow',
        "author": 'Daniel Kahneman',
        "genre": 'selfhelp',
        "status": 'currently_reading',
        "rating": None,
        "review": 'Dense but insightful.',
        "date_finished": None,
        "purchase_link": 'https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.ceqZU8DyU2py75144OBkf9zHGHjPP8egj_5tnRTf3vZc7v-rFwkn29r_fX2nBefD6dfhTUj9UD9G8IwNsRiuc42UPN1FqyYgXTMoTfyXj2atUptHG8q4-D7DP86sxOAWwwvMGx49bU5Ok6BDtzh9-AJRrCec6zQvxmtsbHP42oqqRxbo616Dif3KX7IsEp-mkOuNqQCqYIzrAfflgrflZSVCLTeTu0-MPoJq_jPqBqE.H-Fk5fjLaBIVxcKtnVFr9AqRE5WbMuuytjnUPBhlCqE&qid=1771697841&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/thinkingfastandslow_obeqjx',
    },
    {
        "title": 'Zero to One',
        "author": 'Peter Thiel',
        "genre": 'nonfiction',
        "status": 'finished',
        "rating": 3,
        "review": 'Interesting perspective, but controversial ideas.',
        "date_finished": '2024-07-02',
        "purchase_link": 'https://www.amazon.com/Peter-Thiel-Zero-One-Paperback/dp/B00QEUZ690/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.Lzp1vy8oDjphfyWJeHEtxRkrdqlKCz7IDWCgVXIttEpjulVQgAbQ8S1WX75FVwfinR2X_wEj4F6EGYo5FrJEk2WqccV6ypi7nFXN9iDke1AZ0dgFmT3ez6ftgEXeta2bH5_rEgkvOd2qfTMSA05LDZHL6yCmkgqnNoH3OYNX1hQq1RwFlIJWY8DxRupEW0RoF6sA4xFu3LbomNYX1_T8o5_otfYtHhxOG_AXoIdVx3k.CEo2B5P3WoLCGInyADpDIlAhlg8Vm567ttd3cQMJGFE&qid=1771795626&sr=1-1',
        "image_url": 'https://res.cloudinary.com/dnxyxrmag/image/upload/v1/media/images/zerotoone_thkcmj',
    },
]

# ===== DEMO LISTS =====
DEMO_LISTS = [
    {
        "name": 'All Time Favorites',
        "books": ['1984', 'Atomic Habits', 'Crime and Punishment', 'Man’s Search for Meaning', 'Meditations', 'Project Hail Mary', 'Steve Jobs', 'The Book Thief', 'The Fellowship of the Ring', 'The Hitchhiker’s Guide to the Galaxy', 'The Martian', 'The Name of the Wind', 'The Pragmatic Programmer'],
    },
    {
        "name": 'Classics I Finally Read',
        "books": ['Crime and Punishment', 'Fahrenheit 451', 'Slaughterhouse-Five', 'The Catcher in the Rye', 'The Great Gatsby'],
    },
    {
        "name": 'Sci-Fi Favorites',
        "books": ['Neuromancer', 'Ready Player One', 'The Hitchhiker’s Guide to the Galaxy', 'The Martian'],
    },
]